.PHONY: dev dev-local dev-env load-env save-env tofu-outputs help
.PHONY: deploy deploy-infra deploy-frontend deploy-plan deploy-destroy
.PHONY: build-frontend build-backend
.PHONY: tofu-init tofu-plan tofu-apply tofu-destroy tofu-validate

# Default target
help:
	@echo "Development targets:"
	@echo "  dev         - Run frontend dev server with OpenTofu outputs loaded"
	@echo "  dev-local   - Run frontend dev server with local .env file"
	@echo "  dev-env     - Show current environment variables from OpenTofu"
	@echo "  load-env    - Load OpenTofu outputs (use: eval \$$(make load-env))"
	@echo "  save-env    - Save OpenTofu outputs to .env file in project root"
	@echo "  tofu-outputs - Show all OpenTofu outputs"
	@echo ""
	@echo "Build targets:"
	@echo "  build-frontend - Build frontend for production"
	@echo "  build-backend  - Build backend Lambda packages"
	@echo ""
	@echo "Infrastructure targets:"
	@echo "  tofu-init    - Initialize OpenTofu backend"
	@echo "  tofu-plan    - Show OpenTofu execution plan"
	@echo "  tofu-apply   - Apply OpenTofu infrastructure changes"
	@echo "  tofu-destroy - Destroy OpenTofu infrastructure"
	@echo "  tofu-validate - Validate OpenTofu configuration"
	@echo ""
	@echo "Deployment targets:"
	@echo "  deploy         - Full deployment (infra + frontend)"
	@echo "  deploy-plan    - Show deployment plan without applying"
	@echo "  deploy-infra   - Deploy infrastructure only"
	@echo "  deploy-frontend - Deploy frontend to Amplify"
	@echo "  deploy-destroy - Destroy all infrastructure"

# Load OpenTofu outputs - outputs shell export commands
# Usage: eval $$(make load-env)
load-env:
	@cd infra && \
	API_URL=$$(tofu output -raw env_api_gateway_url 2>/dev/null); \
	TABLE_NAME=$$(tofu output -raw env_dynamodb_table_name 2>/dev/null); \
	COGNITO_USER_POOL_ID=$$(tofu output -raw cognito_user_pool_id 2>/dev/null); \
	COGNITO_CLIENT_ID=$$(tofu output -raw cognito_user_pool_client_id 2>/dev/null); \
	COGNITO_DOMAIN=$$(tofu output -raw cognito_user_pool_domain 2>/dev/null); \
	COGNITO_REGION=$$(tofu output -raw cognito_user_pool_id 2>/dev/null | cut -d'_' -f1); \
	COGNITO_HOSTED_UI_URL=$$(tofu output -raw cognito_hosted_ui_url 2>/dev/null); \
	if [ -n "$$API_URL" ]; then \
	  echo "export API_GATEWAY_URL=$$API_URL"; \
	  echo "export VITE_API_URL=$$API_URL"; \
	fi; \
	if [ -n "$$TABLE_NAME" ]; then \
	  echo "export DYNAMODB_TABLE_NAME=$$TABLE_NAME"; \
	fi; \
	if [ -n "$$COGNITO_USER_POOL_ID" ]; then \
	  echo "export VITE_COGNITO_USER_POOL_ID=$$COGNITO_USER_POOL_ID"; \
	fi; \
	if [ -n "$$COGNITO_CLIENT_ID" ]; then \
	  echo "export VITE_COGNITO_CLIENT_ID=$$COGNITO_CLIENT_ID"; \
	fi; \
	if [ -n "$$COGNITO_DOMAIN" ]; then \
	  echo "export VITE_COGNITO_DOMAIN=$$COGNITO_DOMAIN"; \
	fi; \
	if [ -n "$$COGNITO_REGION" ]; then \
	  echo "export VITE_COGNITO_REGION=$$COGNITO_REGION"; \
	fi; \
	if [ -n "$$COGNITO_HOSTED_UI_URL" ]; then \
	  echo "export VITE_COGNITO_HOSTED_UI_URL=$$COGNITO_HOSTED_UI_URL"; \
	fi; \
	echo "export VITE_COGNITO_REDIRECT_URI=http://localhost:5173/auth/callback"

# Save OpenTofu outputs to .env file in project root
save-env:
	@echo "Saving OpenTofu outputs to .env file..."
	@cd infra && \
	API_URL=$$(tofu output -raw env_api_gateway_url 2>/dev/null); \
	TABLE_NAME=$$(tofu output -raw env_dynamodb_table_name 2>/dev/null); \
	COGNITO_USER_POOL_ID=$$(tofu output -raw cognito_user_pool_id 2>/dev/null); \
	COGNITO_CLIENT_ID=$$(tofu output -raw cognito_user_pool_client_id 2>/dev/null); \
	COGNITO_DOMAIN=$$(tofu output -raw cognito_user_pool_domain 2>/dev/null); \
	COGNITO_REGION=$$(tofu output -raw cognito_user_pool_id 2>/dev/null | cut -d'_' -f1); \
	COGNITO_HOSTED_UI_URL=$$(tofu output -raw cognito_hosted_ui_url 2>/dev/null); \
	cd .. && \
	echo "# Generated by 'make save-env' - DO NOT EDIT MANUALLY" > .env; \
	echo "# Run 'make save-env' to regenerate this file from OpenTofu outputs" >> .env; \
	echo "" >> .env; \
	echo "# API Configuration" >> .env; \
	if [ -n "$$API_URL" ]; then \
	  echo "VITE_API_URL=$$API_URL" >> .env; \
	  echo "API_GATEWAY_URL=$$API_URL" >> .env; \
	else \
	  echo "# VITE_API_URL=" >> .env; \
	  echo "# API_GATEWAY_URL=" >> .env; \
	fi; \
	echo "" >> .env; \
	echo "# DynamoDB Configuration" >> .env; \
	if [ -n "$$TABLE_NAME" ]; then \
	  echo "DYNAMODB_TABLE_NAME=$$TABLE_NAME" >> .env; \
	else \
	  echo "# DYNAMODB_TABLE_NAME=" >> .env; \
	fi; \
	echo "" >> .env; \
	echo "# Cognito Configuration" >> .env; \
	if [ -n "$$COGNITO_USER_POOL_ID" ]; then \
	  echo "VITE_COGNITO_USER_POOL_ID=$$COGNITO_USER_POOL_ID" >> .env; \
	else \
	  echo "# VITE_COGNITO_USER_POOL_ID=" >> .env; \
	fi; \
	if [ -n "$$COGNITO_CLIENT_ID" ]; then \
	  echo "VITE_COGNITO_CLIENT_ID=$$COGNITO_CLIENT_ID" >> .env; \
	else \
	  echo "# VITE_COGNITO_CLIENT_ID=" >> .env; \
	fi; \
	if [ -n "$$COGNITO_DOMAIN" ]; then \
	  echo "VITE_COGNITO_DOMAIN=$$COGNITO_DOMAIN" >> .env; \
	else \
	  echo "# VITE_COGNITO_DOMAIN=" >> .env; \
	fi; \
	if [ -n "$$COGNITO_REGION" ]; then \
	  echo "VITE_COGNITO_REGION=$$COGNITO_REGION" >> .env; \
	else \
	  echo "# VITE_COGNITO_REGION=" >> .env; \
	fi; \
	if [ -n "$$COGNITO_HOSTED_UI_URL" ]; then \
	  echo "VITE_COGNITO_HOSTED_UI_URL=$$COGNITO_HOSTED_UI_URL" >> .env; \
	else \
	  echo "# VITE_COGNITO_HOSTED_UI_URL=" >> .env; \
	fi; \
	echo "VITE_COGNITO_REDIRECT_URI=http://localhost:5173/auth/callback" >> .env; \
	echo "" >> .env; \
	echo "✓ .env file created/updated in project root"

# Show environment outputs
dev-env:
	@echo "OpenTofu Environment Outputs:"
	@cd infra && \
	API_URL=$$(tofu output -raw env_api_gateway_url 2>/dev/null); \
	TABLE_NAME=$$(tofu output -raw env_dynamodb_table_name 2>/dev/null); \
	[ -n "$$API_URL" ] && echo "  env_api_gateway_url: $$API_URL" || echo "  env_api_gateway_url: (not set)"; \
	[ -n "$$TABLE_NAME" ] && echo "  env_dynamodb_table_name: $$TABLE_NAME" || echo "  env_dynamodb_table_name: (not set)"

# Show all OpenTofu outputs
tofu-outputs:
	@cd infra && tofu output

# Run dev server with OpenTofu outputs loaded
dev:
	@echo "Loading OpenTofu outputs..."
	@cd infra && \
	API_URL=$$(tofu output -raw env_api_gateway_url 2>/dev/null || echo ""); \
	TABLE_NAME=$$(tofu output -raw env_dynamodb_table_name 2>/dev/null || echo ""); \
	COGNITO_USER_POOL_ID=$$(tofu output -raw cognito_user_pool_id 2>/dev/null || echo ""); \
	COGNITO_CLIENT_ID=$$(tofu output -raw cognito_user_pool_client_id 2>/dev/null || echo ""); \
	COGNITO_DOMAIN=$$(tofu output -raw cognito_user_pool_domain 2>/dev/null || echo ""); \
	COGNITO_REGION=$$(tofu output -raw cognito_user_pool_id 2>/dev/null | cut -d'_' -f1 || echo ""); \
	COGNITO_HOSTED_UI_URL=$$(tofu output -raw cognito_hosted_ui_url 2>/dev/null || echo ""); \
	if [ -z "$$API_URL" ]; then \
	  echo "⚠️  Warning: env_api_gateway_url not found. Run 'tofu apply' in infra/ first."; \
	fi; \
	if [ -z "$$COGNITO_CLIENT_ID" ]; then \
	  echo "⚠️  Warning: Cognito configuration not found. Run 'tofu apply' in infra/ first."; \
	fi; \
	cd ../fm-frontend && \
	VITE_API_URL="$$API_URL" \
	DYNAMODB_TABLE_NAME="$$TABLE_NAME" \
	VITE_COGNITO_USER_POOL_ID="$$COGNITO_USER_POOL_ID" \
	VITE_COGNITO_CLIENT_ID="$$COGNITO_CLIENT_ID" \
	VITE_COGNITO_DOMAIN="$$COGNITO_DOMAIN" \
	VITE_COGNITO_REGION="$$COGNITO_REGION" \
	VITE_COGNITO_HOSTED_UI_URL="$$COGNITO_HOSTED_UI_URL" \
	VITE_COGNITO_REDIRECT_URI="http://localhost:5173/auth/callback" \
	npm run dev -- --clearScreen false

# Run dev server with local .env file
dev-local:
	@echo "Loading environment from local .env file..."
	@if [ ! -f .env ]; then \
	  echo "⚠️  Warning: .env file not found in project root"; \
	  echo "   Run 'make save-env' to create it from OpenTofu outputs, or create it manually."; \
	  exit 1; \
	fi; \
	bash -c 'set -a && source .env && set +a && cd fm-frontend && npm run dev -- --clearScreen false'

# Build targets
build-frontend:
	@echo "Building frontend..."
	@cd infra && \
	API_URL=$$(tofu output -raw env_api_gateway_url 2>/dev/null || echo ""); \
	cd ../fm-frontend && \
	if [ -n "$$API_URL" ]; then \
	  echo "Building with API URL: $$API_URL"; \
	  VITE_API_URL="$$API_URL" npm run build; \
	else \
	  echo "⚠️  Warning: API Gateway URL not found. Building without VITE_API_URL."; \
	  echo "   Run 'make deploy-infra' first to set up infrastructure."; \
	  npm run build; \
	fi
	@echo "✓ Frontend build complete"

build-backend:
	@echo "Building backend Lambda packages..."
	@cd infra && tofu init -upgrade
	@echo "✓ Backend packages will be built during tofu apply"

# OpenTofu infrastructure targets
tofu-init:
	@echo "Initializing OpenTofu..."
	@cd infra && tofu init
	@echo "✓ OpenTofu initialized"

tofu-validate:
	@echo "Validating OpenTofu configuration..."
	@cd infra && tofu validate
	@echo "✓ Configuration validated"

tofu-plan:
	@echo "Creating OpenTofu execution plan..."
	@cd infra && \
	if [ -f terraform.tfvars ]; then \
	  tofu plan -var-file=terraform.tfvars; \
	else \
	  echo "⚠️  Warning: terraform.tfvars not found. Using defaults or environment variables."; \
	  echo "   Create infra/terraform.tfvars from infra/terraform.tfvars.example"; \
	  tofu plan; \
	fi
	@echo "✓ Plan complete"

tofu-apply:
	@echo "Applying OpenTofu infrastructure..."
	@cd infra && \
	if [ -f terraform.tfvars ]; then \
	  tofu apply -auto-approve -var-file=terraform.tfvars; \
	else \
	  echo "⚠️  Warning: terraform.tfvars not found. Using defaults or environment variables."; \
	  echo "   Create infra/terraform.tfvars from infra/terraform.tfvars.example"; \
	  tofu apply -auto-approve; \
	fi
	@echo "✓ Infrastructure deployed"

tofu-destroy:
	@echo "⚠️  WARNING: This will destroy all infrastructure!"
	@echo "OpenTofu will prompt for confirmation..."
	@cd infra && tofu destroy
	@echo "✓ Infrastructure destroyed"

# Deployment targets
deploy-plan: tofu-validate tofu-plan
	@echo "✓ Deployment plan ready. Run 'make deploy-infra' to apply."

deploy-infra: tofu-validate
	@echo "Checking for terraform.tfvars..."
	@cd infra && \
	if [ ! -f terraform.tfvars ]; then \
	  echo "⚠️  Warning: terraform.tfvars not found!"; \
	  echo "   Create it from terraform.tfvars.example and add your OpenAI API key."; \
	  echo "   Continuing with defaults/environment variables..."; \
	fi
	@$(MAKE) tofu-apply
	@echo "✓ Infrastructure deployed successfully"
	@echo "Run 'make tofu-outputs' to see deployment outputs"

deploy-frontend: build-frontend
	@echo "Deploying frontend to Amplify..."
	@cd infra && \
	AMPLIFY_APP_ID=$$(tofu output -raw amplify_app_id 2>/dev/null); \
	AMPLIFY_BRANCH=$$(tofu output -raw amplify_branch 2>/dev/null || echo "main"); \
	if [ -z "$$AMPLIFY_APP_ID" ]; then \
	  echo "❌ Error: Amplify app ID not found. Run 'make deploy-infra' first."; \
	  exit 1; \
	fi; \
	cd ../fm-frontend && \
	if [ ! -d dist ]; then \
	  echo "❌ Error: Frontend build not found. Run 'make build-frontend' first."; \
	  exit 1; \
	fi; \
	echo "Creating deployment package..."; \
	# Include amplify.yml if it exists for proper configuration \
	if [ -f amplify.yml ]; then \
	  cp amplify.yml dist/ 2>/dev/null || true; \
	fi; \
	# For manual deployments, zip should contain files at root \
	cd dist && \
	zip -r ../frontend-deploy.zip . > /dev/null 2>&1 && \
	cd .. && \
	echo "Deploying to Amplify app $$AMPLIFY_APP_ID, branch $$AMPLIFY_BRANCH..."; \
	if command -v aws >/dev/null 2>&1; then \
	  echo "Creating deployment job..."; \
	  JOB_INFO=$$(aws amplify create-deployment \
	    --app-id "$$AMPLIFY_APP_ID" \
	    --branch-name "$$AMPLIFY_BRANCH" \
	    --output json 2>/dev/null); \
	  if [ $$? -eq 0 ] && [ -n "$$JOB_INFO" ]; then \
	    JOB_ID=$$(echo "$$JOB_INFO" | grep -o '"jobId"[^,}]*' | cut -d'"' -f4); \
	    ZIP_UPLOAD_URL=$$(echo "$$JOB_INFO" | grep -o '"zipUploadUrl"[^,}]*' | cut -d'"' -f4); \
	    if [ -n "$$JOB_ID" ] && [ -n "$$ZIP_UPLOAD_URL" ]; then \
	      echo "Uploading artifacts to Amplify (job: $$JOB_ID)..."; \
	      curl -X PUT "$$ZIP_UPLOAD_URL" -H "Content-Type: application/zip" --upload-file frontend-deploy.zip > /dev/null 2>&1; \
	      if [ $$? -eq 0 ]; then \
	        echo "Starting deployment..."; \
	        aws amplify start-deployment \
	          --app-id "$$AMPLIFY_APP_ID" \
	          --branch-name "$$AMPLIFY_BRANCH" \
	          --job-id "$$JOB_ID" > /dev/null 2>&1; \
	        echo "✓ Deployment started successfully"; \
	        echo "  Job ID: $$JOB_ID"; \
	        echo "  Check status: aws amplify get-job --app-id $$AMPLIFY_APP_ID --branch-name $$AMPLIFY_BRANCH --job-id $$JOB_ID"; \
	      else \
	        echo "⚠️  Failed to upload artifacts. Trying alternative method..."; \
	        echo "   Job ID: $$JOB_ID"; \
	        echo "   Upload URL: $$ZIP_UPLOAD_URL"; \
	        echo "   Package: $$(pwd)/frontend-deploy.zip"; \
	      fi; \
	    else \
	      echo "⚠️  Could not parse deployment response."; \
	      echo "   Response: $$JOB_INFO"; \
	    fi; \
	  else \
	    echo "⚠️  Could not create deployment via AWS CLI."; \
	    echo "   Ensure AWS credentials are configured and Amplify app exists."; \
	    echo "   App ID: $$AMPLIFY_APP_ID"; \
	    echo "   Branch: $$AMPLIFY_BRANCH"; \
	    echo "   Build package: $$(pwd)/frontend-deploy.zip"; \
	    echo "   Deploy manually via AWS Console if needed."; \
	  fi; \
	else \
	  echo "⚠️  AWS CLI not found. Build package created at:"; \
	  echo "   $$(pwd)/frontend-deploy.zip"; \
	  echo "   Install AWS CLI and configure credentials, or deploy manually via AWS Console."; \
	  echo "   App ID: $$AMPLIFY_APP_ID"; \
	  echo "   Branch: $$AMPLIFY_BRANCH"; \
	fi; \
	rm -f frontend-deploy.zip 2>/dev/null || true

deploy: deploy-infra deploy-frontend
	@echo "✓ Full deployment complete"
	@cd infra && \
	AMPLIFY_URL=$$(tofu output -raw amplify_app_url 2>/dev/null || echo ""); \
	if [ -n "$$AMPLIFY_URL" ]; then \
	  echo "Frontend URL: $$AMPLIFY_URL"; \
	fi

deploy-destroy: tofu-destroy
	@echo "✓ Infrastructure destroyed"

